### ISSUE TITLE
新的两个导致TTKMusicPlayer和qmmp崩溃的.v2m文件

### ISSUE THREAD

**Issue by flyxyz123** [TTK-qmmp/qmmp-v2m#1]
<https://github.com/Greedysky/TTKMusicplayer/issues/101> 这个issue的解决方法有瑕疵，这两个以前能打开的.v2m文件现在会导致TTKMusicPlayer和qmmp崩溃：[new_badv2m.tar.gz](https://github.com/TTK-qmmp/qmmp-v2m/files/6874169/new_badv2m.tar.gz)

我看了下代码，下面76-79行好像是原先的解决方法
https://github.com/TTK-qmmp/qmmp-v2m/blob/0d500aeec727823a868820fb04b024094707f694/libv2m/v2mconv.cpp#L76-L87
这解决方法有个问题是附件中的两个.v2m文件`base.spsize`大于8192，以前他们是进入下面几行的中的`if`没问题，现在进入`else`不知为何就崩溃了
https://github.com/TTK-qmmp/qmmp-v2m/blob/0d500aeec727823a868820fb04b024094707f694/libv2m/v2mplayer.cpp#L89-L106
我的解决方法是v2mconv.cpp中先判断`if (base.spsize < 0 || base.spsize > 8192) `然后再`else if (base.spsize > inlen - (d - inptr)) `当然直接`if (base.spsize < 0 || base.spsize > 8192 || (base.spsize > inlen - (d - inptr))) `也行但没必要，鬼知道这个8192到底是啥玩意。当然那个没啥用的`d += base.spsize;`也要移到下面或者直接删掉。v2mplayer.cpp的原理我没怎么研究，直接改v2mconv.cpp算是个workaround吧，反正能解决问题了，详见PR

只在arch linux + qmmp上测试过，能读取全部v2m文件不崩溃了

要是有啥方法能让读取文件出错时别崩溃直接闪退就好了

**Comment by flyxyz123** [comment]
以后要再出问题的话，可以试着改成
```C
if (base.spsize < 0 || base.spsize > 8192 || (base.spsize > inlen - (d - inptr)))
 { 
   base.spsize     = 0; 
   base.speechdata = 0; 
 } 
```
或者尝试修改 v2mplayer.cpp

**Comment by Greedysky** [comment]
感谢，今晚我看一下
