### ISSUE TITLE
v2m音乐错误总时长导致提前结束

### ISSUE THREAD

**Issue by flyxyz123** [TTK-qmmp/qmmp-v2m#3]
arch linux, qmmp 2.0.0

新的几个commit后很多v2m音乐会提前结束。研究了一下，发现好像是这里的问题：
https://github.com/TTK-qmmp/qmmp-v2m/blob/fcdbec0f420f9cc0d8d24a70c480fd179b93d83a/libv2m/v2mplayer.cpp#L406-L409
相关commit:
https://github.com/TTK-qmmp/qmmp-v2m/commit/fcdbec0f420f9cc0d8d24a70c480fd179b93d83a#diff-ae6d3d302ede7436f27d122f363f623397032b5ae8bb5f28a655b4336f372457L404-R408

我感觉我本地大部v2m文件`maxtime`是错误的，也有可能`timediv` 是错误的，总之大部分文件计算出来的总时长都是错的，大部分音乐实际时长远大于显示时长，这会导致达到显示时长后`((m_base.maxtime * m_base.timediv) > m_state.cursmpl)`为假从而退出。

真要补这个bug的话得找个方法计算出准确的总时长，但我感觉错误总时长是文件头本身数据就是错的，不太好解决。或者workaround一下，还是用commit之前的`return m_base.valid && m_state.state == PlayerState::PLAYING;`，见pull request。我是无所谓总时长错误，感觉除了v2m以外很多其他格式总时长也都是错的，目前workaround一下不提前退出我就满意了。

我本地所有v2m文件供参考，来源<http://keygenmusic.net>：
[v2m.tar.gz](https://github.com/TTK-qmmp/qmmp-v2m/files/7159854/v2m.tar.gz)
大部分实际时长远大于显示时长。小部分实际时长远小于显示时长，那几个总时长1个小时多的就是例子，这种好像没影响。小部分实际时长和显示时长相符。如果用qmmp的话打开 waveform seek bar 很容易能分辨出来这三种。

**Comment by Greedysky** [comment]
感谢，如果大部分v2m的文件头数据是错误的话，那么后者的计算方法就不可靠了。可以考虑暂时屏蔽它，虽然在时长显示上有瑕疵。
